apiVersion: v2
name: bubu
description: A Helm chart for BubuStack. Deploys BuBu Operator with it's dependencies into your cluster.
type: application
version: 0.0.1
appVersion: "0.0.1"
home: https://github.com/bubustack/

dependencies:
  - name: nats
    repository: "https://nats-io.github.io/k8s/helm/charts/"
    version: "1.3.1"
    