apiVersion: bubu.sh/v1alpha1
kind: Engram
metadata:
  name: test-http-client
  namespace: default
spec:
  engine:
    templateRef: http-client
    mode: job
    imagePullPolicy: Never
  with:
    timeout: "30s"
    verify_ssl: true
---
apiVersion: bubu.sh/v1alpha1
kind: Story
metadata:
  name: test-http-story
  namespace: default
spec:
  steps:
    - name: "test-http-get-1"
      ref: test-http-client
      with:
        url: "https://httpbin.org/get"
        method: "GET"
        headers:
          User-Agent: "Bobrapet-Test/1.0"
    - name: "test-http-get-2"
      ref: test-http-client
      with:
        url: "https://httpbin.org/get"
        method: "GET"
        headers:
          User-Agent: "Bobrapet-Test/1.0"
    - name: "test-http-get-3"
      ref: test-http-client
      with:
        url: "https://httpbin.org/get"
        method: "GET"
        headers:
          User-Agent: "Bobrapet-Test/1.0"

    - name: "test-http-get-4"
      ref: test-http-client
      with:
        url: "https://httpbin.org/get"
        method: "GET"
        headers:
          User-Agent: "Bobrapet-Test/1.0"
    
    - name: "test-http-get-5"
      ref: test-http-client
      with:
        url: "https://httpbin.org/get"
        method: "GET"
        headers:
          User-Agent: "Bobrapet-Test/1.0"
---
apiVersion: runs.bubu.sh/v1alpha1
kind: StoryRun
metadata:
  name: test-http-run
  namespace: default
spec:
  storyRef: test-http-story
  inputs: {}
