apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
- operator-config.yaml
images:
- name: ghcr.io/bubustack/bobrapet
  newName: example.com/bobrapet
  newTag: v0.0.1
