apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-manager-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bubu.sh
  resources:
  - projects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bubu.sh
  resources:
  - projects/finalizers
  verbs:
  - update
- apiGroups:
  - bubu.sh
  resources:
  - projects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.istio.io
  resources:
  - gateways
  - virtualservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - transport.bubu.sh
  resources:
  - https
  - websockets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - transport.bubu.sh
  resources:
  - https/finalizers
  - websockets/finalizers
  verbs:
  - update
- apiGroups:
  - transport.bubu.sh
  resources:
  - https/status
  - websockets/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-manager-rolebinding
  labels:
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "chart.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
