---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bubu.sh
  resources:
  - engrams
  - impulses
  - stories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bubu.sh
  resources:
  - engrams/finalizers
  - impulses/finalizers
  - stories/finalizers
  verbs:
  - update
- apiGroups:
  - bubu.sh
  resources:
  - engrams/status
  - impulses/status
  - stories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - catalog.bubu.sh
  resources:
  - engramtemplates
  - impulsetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catalog.bubu.sh
  resources:
  - engramtemplates/finalizers
  - impulsetemplates/finalizers
  verbs:
  - update
- apiGroups:
  - catalog.bubu.sh
  resources:
  - engramtemplates/status
  - impulsetemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - runs.bubu.sh
  resources:
  - stepruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - runs.bubu.sh
  resources:
  - stepruns/finalizers
  verbs:
  - update
- apiGroups:
  - runs.bubu.sh
  resources:
  - stepruns/status
  - storyruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - runs.bubu.sh
  resources:
  - storyruns
  verbs:
  - get
  - list
  - patch
  - update
  - watch
