#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENGRAMS_DIR="${ROOT_DIR}/../engrams"

if [[ ! -d "${ENGRAMS_DIR}" ]]; then
  echo "Expected sibling engrams repo at ${ENGRAMS_DIR}" >&2
  exit 1
fi

sync_templates() {
  local kind="$1"   # engram or impulse
  local pattern="$2" # Engram.yaml or Impulse.yaml
  local output="$3"
  local header="$4"

  printf "# %s\n" "$header" >"${output}"
  printf "# Generated by hack/sync-templates.sh. Do not edit manually.\n" >>"${output}"

  local found=0
  while IFS= read -r -d '' file; do
    found=1
    printf "\n" >>"${output}"
    cat "$file" >>"${output}"
    printf "\n" >>"${output}"
  done < <(find "${ENGRAMS_DIR}" -maxdepth 2 -type f -name "$pattern" -print0 | sort -z)

  if [[ $found -eq 0 ]]; then
    printf "# No %s templates found under %s\n" "$kind" "$ENGRAMS_DIR" >>"${output}"
  fi
}

sync_templates "engram" "Engram.yaml" "${ROOT_DIR}/config/samples/catalog_v1alpha1_engramtemplate.yaml" \
  "Aggregated EngramTemplate samples from sibling engram repositories"

sync_templates "impulse" "Impulse.yaml" "${ROOT_DIR}/config/samples/catalog_v1alpha1_impulsetemplate.yaml" \
  "Aggregated ImpulseTemplate samples from sibling engram repositories"
