## Append samples of your project ##
resources:
- v1alpha1_story.yaml
- v1alpha1_engram.yaml
- v1alpha1_impulse.yaml
- runs_v1alpha1_storyrun.yaml
- runs_v1alpha1_steprun.yaml
- catalog_v1alpha1_engramtemplate.yaml
- catalog_v1alpha1_impulsetemplate.yaml
- transport_v1alpha1_transport.yaml
- transport_v1alpha1_transportbinding.yaml
- policy_v1alpha1_referencegrant.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
