apiVersion: policy.bubustack.io/v1alpha1
kind: ReferenceGrant
metadata:
  labels:
    app.kubernetes.io/name: bobrapet
    app.kubernetes.io/managed-by: kustomize
  name: referencegrant-sample
spec:
  # Template sample. Populate this spec with a valid ReferenceGrant before applying.
