apiVersion: transport.bubu.sh/v1alpha1
kind: HTTP
metadata:
  name: productpage
  namespace: book-info-service  # Namespace matches the hyphenated project name
spec:
  path: /api/productpage
  destinations:
    - nodeType: HTTPServer
      nodeName: productpage-service
  image: docker.io/istio/examples-bookinfo-productpage-v1:1.16.2
  imagePullPolicy: IfNotPresent
  replicas: 1 