apiVersion: bubustack.io/v1alpha1
kind: Story
metadata:
  labels:
    app.kubernetes.io/name: bobrapet
    app.kubernetes.io/managed-by: kustomize
  name: story-sample
spec:
  # Template sample. Populate this spec with a valid Story before applying.
