apiVersion: bubustack.io/v1alpha1
kind: Impulse
metadata:
  namespace: default
  name: impulse-sample
spec:
  templateRef:
    name: impulsetemplate-sample
  storyRef:
    name: summarize-website-story
    namespace: default
  execution:
    debug: true
  with:
    eventTypes:
      - push
      - pull_request
    repositoryAllowList:
      - bubustack/*
    secretKey: WEBHOOK_SECRET
  secrets:
    github: github-webhook-secret
