//go:build !ignore_autogenerated

/*
Copyright 2025 BubuStack.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/bubustack/bobrapet/pkg/refs"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AudioBinding) DeepCopyInto(out *AudioBinding) {
	*out = *in
	if in.Codecs != nil {
		in, out := &in.Codecs, &out.Codecs
		*out = make([]AudioCodec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AudioBinding.
func (in *AudioBinding) DeepCopy() *AudioBinding {
	if in == nil {
		return nil
	}
	out := new(AudioBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AudioCodec) DeepCopyInto(out *AudioCodec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AudioCodec.
func (in *AudioCodec) DeepCopy() *AudioCodec {
	if in == nil {
		return nil
	}
	out := new(AudioCodec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BinaryBinding) DeepCopyInto(out *BinaryBinding) {
	*out = *in
	if in.MimeTypes != nil {
		in, out := &in.MimeTypes, &out.MimeTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BinaryBinding.
func (in *BinaryBinding) DeepCopy() *BinaryBinding {
	if in == nil {
		return nil
	}
	out := new(BinaryBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Transport) DeepCopyInto(out *Transport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Transport.
func (in *Transport) DeepCopy() *Transport {
	if in == nil {
		return nil
	}
	out := new(Transport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Transport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportBinding) DeepCopyInto(out *TransportBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportBinding.
func (in *TransportBinding) DeepCopy() *TransportBinding {
	if in == nil {
		return nil
	}
	out := new(TransportBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransportBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportBindingList) DeepCopyInto(out *TransportBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TransportBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportBindingList.
func (in *TransportBindingList) DeepCopy() *TransportBindingList {
	if in == nil {
		return nil
	}
	out := new(TransportBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransportBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportBindingSpec) DeepCopyInto(out *TransportBindingSpec) {
	*out = *in
	if in.StoryRunRef != nil {
		in, out := &in.StoryRunRef, &out.StoryRunRef
		*out = new(refs.StoryRunReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Audio != nil {
		in, out := &in.Audio, &out.Audio
		*out = new(AudioBinding)
		(*in).DeepCopyInto(*out)
	}
	if in.Video != nil {
		in, out := &in.Video, &out.Video
		*out = new(VideoBinding)
		(*in).DeepCopyInto(*out)
	}
	if in.Binary != nil {
		in, out := &in.Binary, &out.Binary
		*out = new(BinaryBinding)
		(*in).DeepCopyInto(*out)
	}
	if in.RawSettings != nil {
		in, out := &in.RawSettings, &out.RawSettings
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportBindingSpec.
func (in *TransportBindingSpec) DeepCopy() *TransportBindingSpec {
	if in == nil {
		return nil
	}
	out := new(TransportBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportBindingStatus) DeepCopyInto(out *TransportBindingStatus) {
	*out = *in
	if in.NegotiatedAudio != nil {
		in, out := &in.NegotiatedAudio, &out.NegotiatedAudio
		*out = new(AudioCodec)
		**out = **in
	}
	if in.NegotiatedVideo != nil {
		in, out := &in.NegotiatedVideo, &out.NegotiatedVideo
		*out = new(VideoCodec)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportBindingStatus.
func (in *TransportBindingStatus) DeepCopy() *TransportBindingStatus {
	if in == nil {
		return nil
	}
	out := new(TransportBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportList) DeepCopyInto(out *TransportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Transport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportList.
func (in *TransportList) DeepCopy() *TransportList {
	if in == nil {
		return nil
	}
	out := new(TransportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportSpec) DeepCopyInto(out *TransportSpec) {
	*out = *in
	if in.SupportedAudio != nil {
		in, out := &in.SupportedAudio, &out.SupportedAudio
		*out = make([]AudioCodec, len(*in))
		copy(*out, *in)
	}
	if in.SupportedVideo != nil {
		in, out := &in.SupportedVideo, &out.SupportedVideo
		*out = make([]VideoCodec, len(*in))
		copy(*out, *in)
	}
	if in.SupportedBinary != nil {
		in, out := &in.SupportedBinary, &out.SupportedBinary
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ConfigSchema != nil {
		in, out := &in.ConfigSchema, &out.ConfigSchema
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultSettings != nil {
		in, out := &in.DefaultSettings, &out.DefaultSettings
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportSpec.
func (in *TransportSpec) DeepCopy() *TransportSpec {
	if in == nil {
		return nil
	}
	out := new(TransportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportStatus) DeepCopyInto(out *TransportStatus) {
	*out = *in
	if in.ValidationErrors != nil {
		in, out := &in.ValidationErrors, &out.ValidationErrors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AvailableAudio != nil {
		in, out := &in.AvailableAudio, &out.AvailableAudio
		*out = make([]AudioCodec, len(*in))
		copy(*out, *in)
	}
	if in.AvailableVideo != nil {
		in, out := &in.AvailableVideo, &out.AvailableVideo
		*out = make([]VideoCodec, len(*in))
		copy(*out, *in)
	}
	if in.AvailableBinary != nil {
		in, out := &in.AvailableBinary, &out.AvailableBinary
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastHeartbeatTime != nil {
		in, out := &in.LastHeartbeatTime, &out.LastHeartbeatTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportStatus.
func (in *TransportStatus) DeepCopy() *TransportStatus {
	if in == nil {
		return nil
	}
	out := new(TransportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoBinding) DeepCopyInto(out *VideoBinding) {
	*out = *in
	if in.Codecs != nil {
		in, out := &in.Codecs, &out.Codecs
		*out = make([]VideoCodec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoBinding.
func (in *VideoBinding) DeepCopy() *VideoBinding {
	if in == nil {
		return nil
	}
	out := new(VideoBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoCodec) DeepCopyInto(out *VideoCodec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoCodec.
func (in *VideoCodec) DeepCopy() *VideoCodec {
	if in == nil {
		return nil
	}
	out := new(VideoCodec)
	in.DeepCopyInto(out)
	return out
}
