//go:build !ignore_autogenerated

/*
Copyright 2025 BubuStack.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/bubustack/bobrapet/pkg/refs"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AudioBinding) DeepCopyInto(out *AudioBinding) {
	*out = *in
	if in.Codecs != nil {
		in, out := &in.Codecs, &out.Codecs
		*out = make([]AudioCodec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AudioBinding.
func (in *AudioBinding) DeepCopy() *AudioBinding {
	if in == nil {
		return nil
	}
	out := new(AudioBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AudioCodec) DeepCopyInto(out *AudioCodec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AudioCodec.
func (in *AudioCodec) DeepCopy() *AudioCodec {
	if in == nil {
		return nil
	}
	out := new(AudioCodec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BinaryBinding) DeepCopyInto(out *BinaryBinding) {
	*out = *in
	if in.MimeTypes != nil {
		in, out := &in.MimeTypes, &out.MimeTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BinaryBinding.
func (in *BinaryBinding) DeepCopy() *BinaryBinding {
	if in == nil {
		return nil
	}
	out := new(BinaryBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Transport) DeepCopyInto(out *Transport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Transport.
func (in *Transport) DeepCopy() *Transport {
	if in == nil {
		return nil
	}
	out := new(Transport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Transport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportBackpressureSettings) DeepCopyInto(out *TransportBackpressureSettings) {
	*out = *in
	if in.Buffer != nil {
		in, out := &in.Buffer, &out.Buffer
		*out = new(TransportBufferSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportBackpressureSettings.
func (in *TransportBackpressureSettings) DeepCopy() *TransportBackpressureSettings {
	if in == nil {
		return nil
	}
	out := new(TransportBackpressureSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportBinding) DeepCopyInto(out *TransportBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportBinding.
func (in *TransportBinding) DeepCopy() *TransportBinding {
	if in == nil {
		return nil
	}
	out := new(TransportBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransportBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportBindingList) DeepCopyInto(out *TransportBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TransportBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportBindingList.
func (in *TransportBindingList) DeepCopy() *TransportBindingList {
	if in == nil {
		return nil
	}
	out := new(TransportBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransportBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportBindingSpec) DeepCopyInto(out *TransportBindingSpec) {
	*out = *in
	if in.StoryRunRef != nil {
		in, out := &in.StoryRunRef, &out.StoryRunRef
		*out = new(refs.StoryRunReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Audio != nil {
		in, out := &in.Audio, &out.Audio
		*out = new(AudioBinding)
		(*in).DeepCopyInto(*out)
	}
	if in.Video != nil {
		in, out := &in.Video, &out.Video
		*out = new(VideoBinding)
		(*in).DeepCopyInto(*out)
	}
	if in.Binary != nil {
		in, out := &in.Binary, &out.Binary
		*out = new(BinaryBinding)
		(*in).DeepCopyInto(*out)
	}
	if in.RawSettings != nil {
		in, out := &in.RawSettings, &out.RawSettings
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportBindingSpec.
func (in *TransportBindingSpec) DeepCopy() *TransportBindingSpec {
	if in == nil {
		return nil
	}
	out := new(TransportBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportBindingStatus) DeepCopyInto(out *TransportBindingStatus) {
	*out = *in
	if in.NegotiatedAudio != nil {
		in, out := &in.NegotiatedAudio, &out.NegotiatedAudio
		*out = new(AudioCodec)
		**out = **in
	}
	if in.NegotiatedVideo != nil {
		in, out := &in.NegotiatedVideo, &out.NegotiatedVideo
		*out = new(VideoCodec)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportBindingStatus.
func (in *TransportBindingStatus) DeepCopy() *TransportBindingStatus {
	if in == nil {
		return nil
	}
	out := new(TransportBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportBufferSettings) DeepCopyInto(out *TransportBufferSettings) {
	*out = *in
	if in.MaxMessages != nil {
		in, out := &in.MaxMessages, &out.MaxMessages
		*out = new(int32)
		**out = **in
	}
	if in.MaxBytes != nil {
		in, out := &in.MaxBytes, &out.MaxBytes
		*out = new(int32)
		**out = **in
	}
	if in.MaxAgeSeconds != nil {
		in, out := &in.MaxAgeSeconds, &out.MaxAgeSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportBufferSettings.
func (in *TransportBufferSettings) DeepCopy() *TransportBufferSettings {
	if in == nil {
		return nil
	}
	out := new(TransportBufferSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportDeliverySettings) DeepCopyInto(out *TransportDeliverySettings) {
	*out = *in
	if in.Replay != nil {
		in, out := &in.Replay, &out.Replay
		*out = new(TransportReplaySettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportDeliverySettings.
func (in *TransportDeliverySettings) DeepCopy() *TransportDeliverySettings {
	if in == nil {
		return nil
	}
	out := new(TransportDeliverySettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportFanInSettings) DeepCopyInto(out *TransportFanInSettings) {
	*out = *in
	if in.Quorum != nil {
		in, out := &in.Quorum, &out.Quorum
		*out = new(int32)
		**out = **in
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.MaxEntries != nil {
		in, out := &in.MaxEntries, &out.MaxEntries
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportFanInSettings.
func (in *TransportFanInSettings) DeepCopy() *TransportFanInSettings {
	if in == nil {
		return nil
	}
	out := new(TransportFanInSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportFlowAckSettings) DeepCopyInto(out *TransportFlowAckSettings) {
	*out = *in
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = new(int32)
		**out = **in
	}
	if in.Bytes != nil {
		in, out := &in.Bytes, &out.Bytes
		*out = new(int32)
		**out = **in
	}
	if in.MaxDelay != nil {
		in, out := &in.MaxDelay, &out.MaxDelay
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportFlowAckSettings.
func (in *TransportFlowAckSettings) DeepCopy() *TransportFlowAckSettings {
	if in == nil {
		return nil
	}
	out := new(TransportFlowAckSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportFlowControlSettings) DeepCopyInto(out *TransportFlowControlSettings) {
	*out = *in
	if in.InitialCredits != nil {
		in, out := &in.InitialCredits, &out.InitialCredits
		*out = new(TransportFlowCredits)
		(*in).DeepCopyInto(*out)
	}
	if in.AckEvery != nil {
		in, out := &in.AckEvery, &out.AckEvery
		*out = new(TransportFlowAckSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.PauseThreshold != nil {
		in, out := &in.PauseThreshold, &out.PauseThreshold
		*out = new(TransportFlowThreshold)
		(*in).DeepCopyInto(*out)
	}
	if in.ResumeThreshold != nil {
		in, out := &in.ResumeThreshold, &out.ResumeThreshold
		*out = new(TransportFlowThreshold)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportFlowControlSettings.
func (in *TransportFlowControlSettings) DeepCopy() *TransportFlowControlSettings {
	if in == nil {
		return nil
	}
	out := new(TransportFlowControlSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportFlowCredits) DeepCopyInto(out *TransportFlowCredits) {
	*out = *in
	if in.Messages != nil {
		in, out := &in.Messages, &out.Messages
		*out = new(int32)
		**out = **in
	}
	if in.Bytes != nil {
		in, out := &in.Bytes, &out.Bytes
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportFlowCredits.
func (in *TransportFlowCredits) DeepCopy() *TransportFlowCredits {
	if in == nil {
		return nil
	}
	out := new(TransportFlowCredits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportFlowThreshold) DeepCopyInto(out *TransportFlowThreshold) {
	*out = *in
	if in.BufferPct != nil {
		in, out := &in.BufferPct, &out.BufferPct
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportFlowThreshold.
func (in *TransportFlowThreshold) DeepCopy() *TransportFlowThreshold {
	if in == nil {
		return nil
	}
	out := new(TransportFlowThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportLane) DeepCopyInto(out *TransportLane) {
	*out = *in
	if in.MaxMessages != nil {
		in, out := &in.MaxMessages, &out.MaxMessages
		*out = new(int32)
		**out = **in
	}
	if in.MaxBytes != nil {
		in, out := &in.MaxBytes, &out.MaxBytes
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportLane.
func (in *TransportLane) DeepCopy() *TransportLane {
	if in == nil {
		return nil
	}
	out := new(TransportLane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportLifecycleSettings) DeepCopyInto(out *TransportLifecycleSettings) {
	*out = *in
	if in.DrainTimeoutSeconds != nil {
		in, out := &in.DrainTimeoutSeconds, &out.DrainTimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.MaxInFlight != nil {
		in, out := &in.MaxInFlight, &out.MaxInFlight
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportLifecycleSettings.
func (in *TransportLifecycleSettings) DeepCopy() *TransportLifecycleSettings {
	if in == nil {
		return nil
	}
	out := new(TransportLifecycleSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportList) DeepCopyInto(out *TransportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Transport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportList.
func (in *TransportList) DeepCopy() *TransportList {
	if in == nil {
		return nil
	}
	out := new(TransportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportMetricsSettings) DeepCopyInto(out *TransportMetricsSettings) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportMetricsSettings.
func (in *TransportMetricsSettings) DeepCopy() *TransportMetricsSettings {
	if in == nil {
		return nil
	}
	out := new(TransportMetricsSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportObservabilitySettings) DeepCopyInto(out *TransportObservabilitySettings) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(TransportMetricsSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Tracing != nil {
		in, out := &in.Tracing, &out.Tracing
		*out = new(TransportTracingSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Watermark != nil {
		in, out := &in.Watermark, &out.Watermark
		*out = new(TransportWatermarkSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportObservabilitySettings.
func (in *TransportObservabilitySettings) DeepCopy() *TransportObservabilitySettings {
	if in == nil {
		return nil
	}
	out := new(TransportObservabilitySettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportPartitioningSettings) DeepCopyInto(out *TransportPartitioningSettings) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Partitions != nil {
		in, out := &in.Partitions, &out.Partitions
		*out = new(int32)
		**out = **in
	}
	if in.Sticky != nil {
		in, out := &in.Sticky, &out.Sticky
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportPartitioningSettings.
func (in *TransportPartitioningSettings) DeepCopy() *TransportPartitioningSettings {
	if in == nil {
		return nil
	}
	out := new(TransportPartitioningSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportRecordingSettings) DeepCopyInto(out *TransportRecordingSettings) {
	*out = *in
	if in.SampleRate != nil {
		in, out := &in.SampleRate, &out.SampleRate
		*out = new(int32)
		**out = **in
	}
	if in.RetentionSeconds != nil {
		in, out := &in.RetentionSeconds, &out.RetentionSeconds
		*out = new(int32)
		**out = **in
	}
	if in.RedactFields != nil {
		in, out := &in.RedactFields, &out.RedactFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportRecordingSettings.
func (in *TransportRecordingSettings) DeepCopy() *TransportRecordingSettings {
	if in == nil {
		return nil
	}
	out := new(TransportRecordingSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportReplaySettings) DeepCopyInto(out *TransportReplaySettings) {
	*out = *in
	if in.RetentionSeconds != nil {
		in, out := &in.RetentionSeconds, &out.RetentionSeconds
		*out = new(int32)
		**out = **in
	}
	if in.CheckpointInterval != nil {
		in, out := &in.CheckpointInterval, &out.CheckpointInterval
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportReplaySettings.
func (in *TransportReplaySettings) DeepCopy() *TransportReplaySettings {
	if in == nil {
		return nil
	}
	out := new(TransportReplaySettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportRoutingRule) DeepCopyInto(out *TransportRoutingRule) {
	*out = *in
	if in.When != nil {
		in, out := &in.When, &out.When
		*out = new(string)
		**out = **in
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(TransportRoutingRuleTarget)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportRoutingRule.
func (in *TransportRoutingRule) DeepCopy() *TransportRoutingRule {
	if in == nil {
		return nil
	}
	out := new(TransportRoutingRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportRoutingRuleTarget) DeepCopyInto(out *TransportRoutingRuleTarget) {
	*out = *in
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportRoutingRuleTarget.
func (in *TransportRoutingRuleTarget) DeepCopy() *TransportRoutingRuleTarget {
	if in == nil {
		return nil
	}
	out := new(TransportRoutingRuleTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportRoutingSettings) DeepCopyInto(out *TransportRoutingSettings) {
	*out = *in
	if in.MaxDownstreams != nil {
		in, out := &in.MaxDownstreams, &out.MaxDownstreams
		*out = new(int32)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]TransportRoutingRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportRoutingSettings.
func (in *TransportRoutingSettings) DeepCopy() *TransportRoutingSettings {
	if in == nil {
		return nil
	}
	out := new(TransportRoutingSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportSpec) DeepCopyInto(out *TransportSpec) {
	*out = *in
	if in.SupportedAudio != nil {
		in, out := &in.SupportedAudio, &out.SupportedAudio
		*out = make([]AudioCodec, len(*in))
		copy(*out, *in)
	}
	if in.SupportedVideo != nil {
		in, out := &in.SupportedVideo, &out.SupportedVideo
		*out = make([]VideoCodec, len(*in))
		copy(*out, *in)
	}
	if in.SupportedBinary != nil {
		in, out := &in.SupportedBinary, &out.SupportedBinary
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Streaming != nil {
		in, out := &in.Streaming, &out.Streaming
		*out = new(TransportStreamingSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigSchema != nil {
		in, out := &in.ConfigSchema, &out.ConfigSchema
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultSettings != nil {
		in, out := &in.DefaultSettings, &out.DefaultSettings
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportSpec.
func (in *TransportSpec) DeepCopy() *TransportSpec {
	if in == nil {
		return nil
	}
	out := new(TransportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportStatus) DeepCopyInto(out *TransportStatus) {
	*out = *in
	if in.ValidationErrors != nil {
		in, out := &in.ValidationErrors, &out.ValidationErrors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AvailableAudio != nil {
		in, out := &in.AvailableAudio, &out.AvailableAudio
		*out = make([]AudioCodec, len(*in))
		copy(*out, *in)
	}
	if in.AvailableVideo != nil {
		in, out := &in.AvailableVideo, &out.AvailableVideo
		*out = make([]VideoCodec, len(*in))
		copy(*out, *in)
	}
	if in.AvailableBinary != nil {
		in, out := &in.AvailableBinary, &out.AvailableBinary
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastHeartbeatTime != nil {
		in, out := &in.LastHeartbeatTime, &out.LastHeartbeatTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportStatus.
func (in *TransportStatus) DeepCopy() *TransportStatus {
	if in == nil {
		return nil
	}
	out := new(TransportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportStreamingSettings) DeepCopyInto(out *TransportStreamingSettings) {
	*out = *in
	if in.Backpressure != nil {
		in, out := &in.Backpressure, &out.Backpressure
		*out = new(TransportBackpressureSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.FlowControl != nil {
		in, out := &in.FlowControl, &out.FlowControl
		*out = new(TransportFlowControlSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Delivery != nil {
		in, out := &in.Delivery, &out.Delivery
		*out = new(TransportDeliverySettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Routing != nil {
		in, out := &in.Routing, &out.Routing
		*out = new(TransportRoutingSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Lanes != nil {
		in, out := &in.Lanes, &out.Lanes
		*out = make([]TransportLane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FanIn != nil {
		in, out := &in.FanIn, &out.FanIn
		*out = new(TransportFanInSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Partitioning != nil {
		in, out := &in.Partitioning, &out.Partitioning
		*out = new(TransportPartitioningSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Lifecycle != nil {
		in, out := &in.Lifecycle, &out.Lifecycle
		*out = new(TransportLifecycleSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Observability != nil {
		in, out := &in.Observability, &out.Observability
		*out = new(TransportObservabilitySettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Recording != nil {
		in, out := &in.Recording, &out.Recording
		*out = new(TransportRecordingSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportStreamingSettings.
func (in *TransportStreamingSettings) DeepCopy() *TransportStreamingSettings {
	if in == nil {
		return nil
	}
	out := new(TransportStreamingSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportTracingSettings) DeepCopyInto(out *TransportTracingSettings) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.SampleRate != nil {
		in, out := &in.SampleRate, &out.SampleRate
		*out = new(int32)
		**out = **in
	}
	if in.SamplePolicy != nil {
		in, out := &in.SamplePolicy, &out.SamplePolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportTracingSettings.
func (in *TransportTracingSettings) DeepCopy() *TransportTracingSettings {
	if in == nil {
		return nil
	}
	out := new(TransportTracingSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportWatermarkSettings) DeepCopyInto(out *TransportWatermarkSettings) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.TimestampSource != nil {
		in, out := &in.TimestampSource, &out.TimestampSource
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportWatermarkSettings.
func (in *TransportWatermarkSettings) DeepCopy() *TransportWatermarkSettings {
	if in == nil {
		return nil
	}
	out := new(TransportWatermarkSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoBinding) DeepCopyInto(out *VideoBinding) {
	*out = *in
	if in.Codecs != nil {
		in, out := &in.Codecs, &out.Codecs
		*out = make([]VideoCodec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoBinding.
func (in *VideoBinding) DeepCopy() *VideoBinding {
	if in == nil {
		return nil
	}
	out := new(VideoBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VideoCodec) DeepCopyInto(out *VideoCodec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VideoCodec.
func (in *VideoCodec) DeepCopy() *VideoCodec {
	if in == nil {
		return nil
	}
	out := new(VideoCodec)
	in.DeepCopyInto(out)
	return out
}
