//go:build !ignore_autogenerated

/*
Copyright 2025 BubuStack.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/bubustack/bobrapet/pkg/enums"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EngramTemplate) DeepCopyInto(out *EngramTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EngramTemplate.
func (in *EngramTemplate) DeepCopy() *EngramTemplate {
	if in == nil {
		return nil
	}
	out := new(EngramTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EngramTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EngramTemplateList) DeepCopyInto(out *EngramTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EngramTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EngramTemplateList.
func (in *EngramTemplateList) DeepCopy() *EngramTemplateList {
	if in == nil {
		return nil
	}
	out := new(EngramTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EngramTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EngramTemplateSpec) DeepCopyInto(out *EngramTemplateSpec) {
	*out = *in
	in.TemplateSpec.DeepCopyInto(&out.TemplateSpec)
	if in.InputSchema != nil {
		in, out := &in.InputSchema, &out.InputSchema
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.OutputSchema != nil {
		in, out := &in.OutputSchema, &out.OutputSchema
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EngramTemplateSpec.
func (in *EngramTemplateSpec) DeepCopy() *EngramTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(EngramTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EngramTemplateStatus) DeepCopyInto(out *EngramTemplateStatus) {
	*out = *in
	in.TemplateStatus.DeepCopyInto(&out.TemplateStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EngramTemplateStatus.
func (in *EngramTemplateStatus) DeepCopy() *EngramTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(EngramTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImpulseTemplate) DeepCopyInto(out *ImpulseTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImpulseTemplate.
func (in *ImpulseTemplate) DeepCopy() *ImpulseTemplate {
	if in == nil {
		return nil
	}
	out := new(ImpulseTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImpulseTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImpulseTemplateList) DeepCopyInto(out *ImpulseTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ImpulseTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImpulseTemplateList.
func (in *ImpulseTemplateList) DeepCopy() *ImpulseTemplateList {
	if in == nil {
		return nil
	}
	out := new(ImpulseTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImpulseTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImpulseTemplateSpec) DeepCopyInto(out *ImpulseTemplateSpec) {
	*out = *in
	in.TemplateSpec.DeepCopyInto(&out.TemplateSpec)
	if in.ContextSchema != nil {
		in, out := &in.ContextSchema, &out.ContextSchema
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImpulseTemplateSpec.
func (in *ImpulseTemplateSpec) DeepCopy() *ImpulseTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ImpulseTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImpulseTemplateStatus) DeepCopyInto(out *ImpulseTemplateStatus) {
	*out = *in
	in.TemplateStatus.DeepCopyInto(&out.TemplateStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImpulseTemplateStatus.
func (in *ImpulseTemplateStatus) DeepCopy() *ImpulseTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(ImpulseTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretDefinition) DeepCopyInto(out *SecretDefinition) {
	*out = *in
	if in.ExpectedKeys != nil {
		in, out := &in.ExpectedKeys, &out.ExpectedKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretDefinition.
func (in *SecretDefinition) DeepCopy() *SecretDefinition {
	if in == nil {
		return nil
	}
	out := new(SecretDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateExecutionPolicy) DeepCopyInto(out *TemplateExecutionPolicy) {
	*out = *in
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = new(TemplateImagePolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(TemplateResourcePolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(TemplateSecurityPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Job != nil {
		in, out := &in.Job, &out.Job
		*out = new(TemplateJobPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Retry != nil {
		in, out := &in.Retry, &out.Retry
		*out = new(TemplateRetryPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(string)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(TemplateServicePolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Probes != nil {
		in, out := &in.Probes, &out.Probes
		*out = new(TemplateProbePolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateExecutionPolicy.
func (in *TemplateExecutionPolicy) DeepCopy() *TemplateExecutionPolicy {
	if in == nil {
		return nil
	}
	out := new(TemplateExecutionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateImagePolicy) DeepCopyInto(out *TemplateImagePolicy) {
	*out = *in
	if in.PullPolicy != nil {
		in, out := &in.PullPolicy, &out.PullPolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateImagePolicy.
func (in *TemplateImagePolicy) DeepCopy() *TemplateImagePolicy {
	if in == nil {
		return nil
	}
	out := new(TemplateImagePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateJobPolicy) DeepCopyInto(out *TemplateJobPolicy) {
	*out = *in
	if in.RecommendedBackoffLimit != nil {
		in, out := &in.RecommendedBackoffLimit, &out.RecommendedBackoffLimit
		*out = new(int32)
		**out = **in
	}
	if in.RecommendedTTLSecondsAfterFinished != nil {
		in, out := &in.RecommendedTTLSecondsAfterFinished, &out.RecommendedTTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
	if in.RecommendedRestartPolicy != nil {
		in, out := &in.RecommendedRestartPolicy, &out.RecommendedRestartPolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateJobPolicy.
func (in *TemplateJobPolicy) DeepCopy() *TemplateJobPolicy {
	if in == nil {
		return nil
	}
	out := new(TemplateJobPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateProbePolicy) DeepCopyInto(out *TemplateProbePolicy) {
	*out = *in
	if in.Liveness != nil {
		in, out := &in.Liveness, &out.Liveness
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.Readiness != nil {
		in, out := &in.Readiness, &out.Readiness
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.Startup != nil {
		in, out := &in.Startup, &out.Startup
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateProbePolicy.
func (in *TemplateProbePolicy) DeepCopy() *TemplateProbePolicy {
	if in == nil {
		return nil
	}
	out := new(TemplateProbePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateResourcePolicy) DeepCopyInto(out *TemplateResourcePolicy) {
	*out = *in
	if in.RecommendedCPURequest != nil {
		in, out := &in.RecommendedCPURequest, &out.RecommendedCPURequest
		*out = new(string)
		**out = **in
	}
	if in.RecommendedCPULimit != nil {
		in, out := &in.RecommendedCPULimit, &out.RecommendedCPULimit
		*out = new(string)
		**out = **in
	}
	if in.RecommendedMemoryRequest != nil {
		in, out := &in.RecommendedMemoryRequest, &out.RecommendedMemoryRequest
		*out = new(string)
		**out = **in
	}
	if in.RecommendedMemoryLimit != nil {
		in, out := &in.RecommendedMemoryLimit, &out.RecommendedMemoryLimit
		*out = new(string)
		**out = **in
	}
	if in.MinCPURequest != nil {
		in, out := &in.MinCPURequest, &out.MinCPURequest
		*out = new(string)
		**out = **in
	}
	if in.MinMemoryRequest != nil {
		in, out := &in.MinMemoryRequest, &out.MinMemoryRequest
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateResourcePolicy.
func (in *TemplateResourcePolicy) DeepCopy() *TemplateResourcePolicy {
	if in == nil {
		return nil
	}
	out := new(TemplateResourcePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateRetryPolicy) DeepCopyInto(out *TemplateRetryPolicy) {
	*out = *in
	if in.RecommendedMaxRetries != nil {
		in, out := &in.RecommendedMaxRetries, &out.RecommendedMaxRetries
		*out = new(int)
		**out = **in
	}
	if in.RecommendedBackoff != nil {
		in, out := &in.RecommendedBackoff, &out.RecommendedBackoff
		*out = new(string)
		**out = **in
	}
	if in.RecommendedBaseDelay != nil {
		in, out := &in.RecommendedBaseDelay, &out.RecommendedBaseDelay
		*out = new(string)
		**out = **in
	}
	if in.RecommendedMaxDelay != nil {
		in, out := &in.RecommendedMaxDelay, &out.RecommendedMaxDelay
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateRetryPolicy.
func (in *TemplateRetryPolicy) DeepCopy() *TemplateRetryPolicy {
	if in == nil {
		return nil
	}
	out := new(TemplateRetryPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateSecurityPolicy) DeepCopyInto(out *TemplateSecurityPolicy) {
	*out = *in
	if in.RequiresNonRoot != nil {
		in, out := &in.RequiresNonRoot, &out.RequiresNonRoot
		*out = new(bool)
		**out = **in
	}
	if in.RequiresReadOnlyRoot != nil {
		in, out := &in.RequiresReadOnlyRoot, &out.RequiresReadOnlyRoot
		*out = new(bool)
		**out = **in
	}
	if in.RequiresNoPrivilegeEscalation != nil {
		in, out := &in.RequiresNoPrivilegeEscalation, &out.RequiresNoPrivilegeEscalation
		*out = new(bool)
		**out = **in
	}
	if in.RecommendedRunAsUser != nil {
		in, out := &in.RecommendedRunAsUser, &out.RecommendedRunAsUser
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateSecurityPolicy.
func (in *TemplateSecurityPolicy) DeepCopy() *TemplateSecurityPolicy {
	if in == nil {
		return nil
	}
	out := new(TemplateSecurityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateServicePolicy) DeepCopyInto(out *TemplateServicePolicy) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]TemplateServicePort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateServicePolicy.
func (in *TemplateServicePolicy) DeepCopy() *TemplateServicePolicy {
	if in == nil {
		return nil
	}
	out := new(TemplateServicePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateServicePort) DeepCopyInto(out *TemplateServicePort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateServicePort.
func (in *TemplateServicePort) DeepCopy() *TemplateServicePort {
	if in == nil {
		return nil
	}
	out := new(TemplateServicePort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateSpec) DeepCopyInto(out *TemplateSpec) {
	*out = *in
	if in.SupportedModes != nil {
		in, out := &in.SupportedModes, &out.SupportedModes
		*out = make([]enums.WorkloadMode, len(*in))
		copy(*out, *in)
	}
	if in.ConfigSchema != nil {
		in, out := &in.ConfigSchema, &out.ConfigSchema
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretSchema != nil {
		in, out := &in.SecretSchema, &out.SecretSchema
		*out = make(map[string]SecretDefinition, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Execution != nil {
		in, out := &in.Execution, &out.Execution
		*out = new(TemplateExecutionPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateSpec.
func (in *TemplateSpec) DeepCopy() *TemplateSpec {
	if in == nil {
		return nil
	}
	out := new(TemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateStatus) DeepCopyInto(out *TemplateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ValidationErrors != nil {
		in, out := &in.ValidationErrors, &out.ValidationErrors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateStatus.
func (in *TemplateStatus) DeepCopy() *TemplateStatus {
	if in == nil {
		return nil
	}
	out := new(TemplateStatus)
	in.DeepCopyInto(out)
	return out
}
